### ISSUE TITLE
unicorn:reload after deploy:restart not useful for preloaded apps

### ISSUE THREAD

**Issue by coffeebite** [sosedoff/capistrano-unicorn#20]
Hi
If apps are preloaded, then unicorn needs to be sent the USR2 signal for a real restart/reload.
Also, I want to handle my own restarts.
Can the addition of unicorn:reload after deploy:restart be made optional via a flag?

**Comment by sosedoff** [comment]
If you look at the current source code, you'll notice that there're 2 tasks:

unicorn:restart - Sends USR2 signal to master process
unicorn:reload - Sends HUP signal to master process

**Comment by coffeebite** [comment]
@sosedoff Indeed. But the unicorn:reload task is the one that is added after deploy:restart.

**Comment by sosedoff** [comment]
True. I'll try to come up with something simple.

**Comment by aviaron** [comment]
Actually there are two things needed to restart a preloaded app:

Send USR2 to the master process (spawns a new master, the pid file will points to it)
Sent QUIT to old master (now pointed to by the pid file appended with ".oldbin")

**Comment by saten** [comment]
@aviaron is right :)
