### ISSUE TITLE
Using with Rainbows!

### ISSUE THREAD

**Issue by dnagir** [sosedoff/capistrano-unicorn#21]
Not an issue at all, rather a question.

I presume it is easily possible to use `capistrno-unicorn` with [rainbows](http://rainbows.rubyforge.org/).

All that's really necessary is to change the `unicorn_bin` to `"rainbows"`.

I'm not sure how much true it is, but I presume it indeed is since Rainbows extends unicorn and all the start/stop/restart stuff is still the same.

Would be much appreciated if someone could confirm or comment on this.

**Comment by sosedoff** [comment]
Im not sure about this, havent used rainbows for production yet. 
Assuming that rainbows uses the same configuration file from unicorn, everything should work fine.

**Comment by dnagir** [comment]
Yes, it uses the same config. So I suppose it should work too...

**Comment by sosedoff** [comment]
Alright then, closing this.

**Comment by dnagir** [comment]
FYI: I've tried it and it seem to "just work".
