### ISSUE TITLE
unicorn:reload not starting a down unicorn

### ISSUE THREAD

**Issue by denen99** [sosedoff/capistrano-unicorn#24]
hello,

 I have been doing some testing and when unicorn is not running, running cap deploy it doesnt start properly. I have been trying to debug but for some reason, when 3 of the 4 nodes are running and 1 node is not, it just drops into sending a USR2 and the node that is down just throws an error about "missing pid, unable to Kill -USR2"

Is there a way to properly start the unicorn if its not running in unicorn:reload as part of after deploy:restart ?

**Comment by sosedoff** [comment]
Hey,

What do you mean by nodes? Different server?

Regarding the issue, im not sure why it happens. If its not running, it should be automatically started.
Do you see anything (warnings, errors) in unicorn log?

**Comment by denen99** [comment]
So i noticed it works when there is only 1 node in the :app roles.  If you have 2 nodes, 1 running and 1 not running, it seems to use the status of the first node and then just try to send a USR2 to every node in the :app role, which of course fails for the nodes that arent running.

**Comment by denen99** [comment]
Here is an example where i listed fe-m01, fe-m02 in :app roles, fe-m01 was running fe-m02 was not.  This is the output i got:

**\* [err :: fe-m02] cat:
**\* [err :: fe-m02] /data/apps/testapp/shared/pids/unicorn.pid
**\* [err :: fe-m02] : No such file or directory
**\* [err :: fe-m02] 
**\* [err :: fe-m02] kill: usage: kill [-s sigspec | -n signum | -sigspec] pid | jobspec ... or kill -l [sigspec]

**Comment by sosedoff** [comment]
Can you seed what `unicorn_get_pid` returns on different nodes ?

**Comment by sosedoff** [comment]
Made a typo, "see"

**Comment by denen99** [comment]
where do you want me to put that debug output ?  I dont see a unicorn_get_pid method in  capistrano_integration.rb

**Comment by sosedoff** [comment]
Method is defined here - https://github.com/sosedoff/capistrano-unicorn/blob/master/lib/capistrano-unicorn/capistrano_integration.rb#L22

You can try to create a task like that: 

```
task :unicorn_debug, :roles => :app do
  logger.important("UNICORN PID: #{unicorn_get_pid}", "Unicorn")
end
```

And then define a hook (right before unicorn tasks): 

```
before :unicorn_restart, :unicorn_debug
```

**Comment by denen99** [comment]
wierd my gem doesnt have that method (0.1.6) I must have an old version.  Especially since my before deploy:restart calls unicorn:reload not unicorn:restart

**Comment by sosedoff** [comment]
I see. Yes, new stuff hasnt been released yet. You can try using git source in bundler:

```
gem 'capistrano-unicorn', :git => 'git://github.com/sosedoff/capistrano-unicorn.git'
```

**Comment by denen99** [comment]
here ya go, 12785 is the correct PID of fe-m01, fe-m02 was down.

Preparing to execute command: "if [ -e /data/apps/test_app/shared/pids/unicorn.pid ]; then echo 'true'; fi"
Execute ([Yes], No, Abort) ?  |y|  
Preparing to execute command: "ps -p $(cat /data/apps/test_app/shared/pids/unicorn.pid) ; true"
Execute ([Yes], No, Abort) ?  |y|  
Preparing to execute command: "cat /data/apps/test_app/shared/pids/unicorn.pid"
Execute ([Yes], No, Abort) ?  |y|  
**\* [Unicorn] UNICORN PID: 12785
Preparing to execute command: "if [ -e /data/apps/test_app/shared/pids/unicorn.pid ]; then echo 'true'; fi"
Execute ([Yes], No, Abort) ?  |y|  
Preparing to execute command: "ps -p $(cat /data/apps/test_app/shared/pids/unicorn.pid) ; true"
Execute ([Yes], No, Abort) ?  |y|  
Preparing to execute command: "cat /data/apps/test_app/shared/pids/unicorn.pid"
Execute ([Yes], No, Abort) ?  |y|  
**\* [Unicorn] Restarting...
Preparing to execute command: "kill -s USR2 12785"
Execute ([Yes], No, Abort) ?  |y|  
**\* [err :: fe-m02 ] bash: line 0: kill: (12785) - No such process
failed: "rvm_path=$HOME/.rvm/ $HOME/.rvm/bin/rvm-shell '1.9.3' -c 'kill -s USR2 12785'" on fe-m02

**Comment by sosedoff** [comment]
Interesting, i would need to run few tests on my local machine. Not sure why its happening. Def a bug. 

Could you provide your capistrano config?

**Comment by denen99** [comment]
sure i will email offline if thats ok.

**Comment by sosedoff** [comment]
Is this still an issue? I believe i did not find a solution at a time. 

Closing for now.

**Comment by denen99** [comment]
yes this is still not working if you have hosts that are a mix of down and running
