### ISSUE TITLE
Refactored code doesn't work with multiple servers

### ISSUE THREAD

**Issue by mgreen** [sosedoff/capistrano-unicorn#29]
As far as I can tell, changing lines like

```
run "#{try_sudo} kill -s QUIT `cat #{unicorn_pid}`"
```

to

```
pid = unicorn_get_pid
unicorn_send_signal(pid, "QUIT")
```

doesn't work with multiple servers. The problem is that _unicorn_get_pid_ uses Capistrano _capture_ which only runs on the first matching node. The result is that the PID from the first server is used to run the 'kill' command on all other servers.

I've looked into using the Capistrano [parallel](https://github.com/capistrano/capistrano/wiki/2.x-DSL-Action-Invocation-Parallel) to try and solve this but was not able figure out a way to capture output easily.

**Comment by jeroenhouben** [comment]
same problem here
the current code doesn't work with multiple app servers

**Comment by sfsekaran** [comment]
Same problem here. It grabs the pid from one server and attempts to kill it on all servers.

**Comment by sfsekaran** [comment]
The following repo seems to contain the beginnings of a fix for this: http://github.com/synctree/capistrano-unicorn

**Comment by sfsekaran** [comment]
That repo does not in fact fix anything. However, I have sent @sosedoff a pull request for a comprehensive refactor which fixes multiple server deployment. (see https://github.com/sosedoff/capistrano-unicorn/pull/30)

**Comment by sosedoff** [comment]
Should be resolved in master
