### ISSUE TITLE
Known problems with capistrano multistage should go into the README

### ISSUE THREAD

**Issue by nhoffmann** [sosedoff/capistrano-unicorn#36]
Please add the [information from your blog post](http://blog.sosedoff.com/2012/01/21/using-capistrano-unicorn-with-multistage-environment/) to the README or at least link to it.

**Comment by sosedoff** [comment]
pull requests are welcome

**Comment by nhoffmann** [comment]
I took the freedom to add the information from your blog post to the capistrano-unicorn wiki. I can also send you a pull request with an updated README that will link to the wiki page. 
Is that OK with you?

**Comment by sosedoff** [comment]
Yes! Thanks for doing it.

**Comment by ealden** [comment]
I've encountered this too.  Should the gem just use `unicorn_env` instead of all three?

**Comment by nhoffmann** [comment]
Yes @ealden. That would have been my next question :)

**Comment by aspiers** [comment]
According to #37 this is now fixed - @sosedoff please can you close it?  And @ealden if by "all three" you mean `rails_env`, `unicorn_env`, and `app_env` then I agree, it seems ridiculous to have three variables and I have submitted #46 for this.

**Comment by sfsekaran** [comment]
@aspiers Sounds good, closing.
