### ISSUE TITLE
Capistrano whines: Please specify the name of your application, set :application, 'foo'

### ISSUE THREAD

**Issue by jonpaul** [sosedoff/capistrano-unicorn#39]
with ruby1.9.3p327, Rails 3.2.8 and Capistrano 2.13.5 adding `require 'capistrano-unicorn'` to the gemfile causes `bundle exec cap deploy` to whine that there is no name specified for my application.

I'm sure there is one, and removing the module require makes `cap deploy` behave as expected.

**Comment by sosedoff** [comment]
I did not test capistrano-unicorn with latest capistrano version, so it might break. There might be some changes with plugin declarations, so i'd have to look into this one. Thanks for the feedback

**Comment by ealden** [comment]
I've encountered this.  Worked around this by setting `:application` first before requiring `capistrano-unicorn`:

```
set :application, "appname"

require "capistrano-unicorn"
```

Seems to be the case with multistage as well, as `:stage` and `default_stage` needs to be set first before a `require "capistrano/ext/multistage".

**Comment by jonpaul** [comment]
Thanks for the fix!

**Comment by williscool** [comment]
You guys are lifesavers thanks

**Comment by scarver2** [comment]
That worked! Thank you, @eaiden. Does anyone know how and if capistrano-unicorn can be modified to account for the application variable in a stage versus the deploy.rb file?

**Comment by ahk** [comment]
This isn't fixed. Changing the order of your requires isn't a fix, it's a workaround for an existing issue.

**Comment by Emerson** [comment]
Would also like to see a fix here.
