### ISSUE TITLE
huge number of unmerged forks

### ISSUE THREAD

**Issue by aspiers** [sosedoff/capistrano-unicorn#45]
I just looked at the [github network graph](https://github.com/sosedoff/capistrano-unicorn/network) and was disappointed to see a huge number of forks with unmerged patches, mostly without corresponding pull requests.  Everybody loses out badly through this fragmentation, so it should be discouraged.

Suggested actions:
- update the README to ask people to submit pull requests
- add comments to commits in forked repositories asking the author to submit a pull request
- proactively merge from forks back into this repo
- make a new release

Thanks for listening!

**Comment by aspiers** [comment]
I just counted at least 39 unmerged forks in the network graph!  This is a lamentable state of affairs!!  :-(  Unless we start contributing back to the original project, we are collectively doomed to constantly reinvent solutions to the same old problems.  F/OSS only survives when people give as well as take, so people, PLEASE start sharing your work.  All it takes is a quick review of the [existing pull requests](https://github.com/sosedoff/capistrano-unicorn/pulls) to ensure someone hasn't already submitted the same fix you have, followed by a single click of the pull request button.  If your name is in this list, then as far as I can see you have an unmerged fork and should seriously think about contributing your fix:
- @sshingler, @brianp, @miepleinc, @drogus, @saten, @matadon, @aviaron, @dorren, @oktoberliner, @astevens, @docwhat, @artiom, @3den, @DaRizat, @reliantsecurity, @IndependentIP, @scarver2, @blue-kite, @mskog, @danielkman, @toao, @gfi, @apptopia, @kennon, @alg, @pleary, @techbang, @Zorros, @ashmckenzie, @thatinstant, @lpgauth, @gfm, @tetsutan, @fernandoalmeida, @talho, @docunext, @pupca, @yournextleap, @dozeo, @orgsync

**Comment by brianp** [comment]
My fork has since become irrelevant. Shortly after I found the docs to properly do what I hacked in my fork.
I do respect this push for PR's though! Cheers

**Comment by aspiers** [comment]
@brianp Thanks for the info! May I suggest you remove the hack from your fork then, to keep the network graph clean?

**Comment by sosedoff** [comment]
@aspiers interested in the commit rights to the repo ?

**Comment by aspiers** [comment]
@sosedoff Sure, I can probably test and merge the odd pull request here and there. I don't have time for much more than that though :-(

**Comment by bobbrez** [comment]
The version bump seems pretty necessary at this point. What's on master for the project currently is not what was deployed to rubygems.

**Comment by aspiers** [comment]
Agreed.

**Comment by BlakeWilliams** [comment]
+1 to bump version.

**Comment by toao** [comment]
My fork has become obsolete, too. Basically I removed the QUIT for the old master within unicorn:restart to get my zero-downtime-setup working (with preload_app=true). This has become irrelevant with the introduction of the duplicate-task in #42

**Comment by sfsekaran** [comment]
I'm sure you know this, but to tic off one of the items on the list, a new release has been made recently.

**Comment by sfsekaran** [comment]
It's an ongoing problem, and we do need to continue to address it. However, this issue doesn't seem like a forum for discussion any longer.

**Comment by sfsekaran** [comment]
I've added a note to the README as suggested.

**Comment by aspiers** [comment]
Thanks!!
