### ISSUE TITLE
`rails_env` / `unicorn_env` / `app_env` are redundant or undocumented

### ISSUE THREAD

**Issue by aspiers** [sosedoff/capistrano-unicorn#46]
It's not at all clear why we need three variables which apparently serve the same purpose:
- `rails_env`
- `unicorn_env`
- `app_env`

If they are really all necessary and serve different purposes then they should be documented properly.  Otherwise they should be collapsed to just one variable, or two at most (since I can just about imagine that someone might want `unicorn_env` to have a different value to `rails_env`).

**Comment by vitoravelino** [comment]
Hey @aspiers! I just saw that I can pass params through the command line and access them inside the deploy file. That would solve that problem that I had without having to change anything at all. 

But I agree that those 3 variables look the same. :+1: to this issue.

**Comment by aspiers** [comment]
I have investigated, and actually they are not the same.  I also found a bug with `app_env` which had independently been reported as #64.  I'm working on a fix for all this now ...

**Comment by sfsekaran** [comment]
@aspiers Is this issue closable, then?

**Comment by aspiers** [comment]
No, it's better to wait until it's resolved before closing.
