### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by sosedoff** [sosedoff/capistrano-unicorn#50]
With more functionality comes more confusion. This project has grown into something that needs tests to continue improving. Otherwise it'll become (or already did) a complete mess.

**Comment by omerisimo** [comment]
I added few basic tests using the [capistrano-spec](https://github.com/technicalpickles/capistrano-spec) gem
You can review commit 4d6f9ae7ee2247a7c21c7ad74c9f4bee18d6a27d on branch [add_tests](https://github.com/omer-g/capistrano-unicorn/tree/add_tests)

Does this look like what you are aiming for?

**Comment by sosedoff** [comment]
@omer-g Thanks, i will take a look.

**Comment by sosedoff** [comment]
@sfsekaran thoughts on this ?

**Comment by sfsekaran** [comment]
I think it's a start. When I get a chance I'm going to test the branch out and merge if it passes. We desperately need a seed test set, so I'm excited @omer-g provided some. Thanks!

**Comment by omerisimo** [comment]
I will tidy it up a bit, and send a pull request.
@sfsekaran, What do you mean by seed tests? What tests did you have in mind?
I will try to add more tests when I will find the time.

**Comment by sfsekaran** [comment]
Sounds good! I saw the pull request. I'll review it soon.

All I meant about seed tests was that we need a small starter set of tests and infrastructure (such as your pull request) that people can use as a reference for their own.

Thanks for the help, Omer!

```
—
```

Sathya Sekaran

**Comment by sfsekaran** [comment]
Closing this, since #71 was merged. We may want to add "testing" issues that signal that a part of the project needs tests.
