### ISSUE TITLE
Manage unicorn via init

### ISSUE THREAD

**Issue by rylwin** [sosedoff/capistrano-unicorn#51]
After having a Linode go down unexpectedly, I realized how much I miss having init control my unicorn service so that it will come back up on system restart. 

I used to do this using moonshine and moonshine_unicorn, but moonshine expects a single app per server and imposes a lot of other related constraints, which is why I moved to capistrano-unicorn.

Because I miss using init so much, I created [capistrano-unicorn-init](https://github.com/ValencePM/capistrano-unicorn-init), which does more or less what this gem does except that it uses init to manage unicorn.

Is there any appetite for merging this init-based solution into this project? Or is it best that I maintain a separate gem for this? What's the advantage of not using init?

@sfsekaran @DavidAllison I enjoyed our conversation on #40. I'm curious to hear what you think of going the init route.

**Comment by DavidAllison** [comment]
@rylwin That makes sense to me. It does seem to generally simplify things. Is the point of this gem to make it work on systems that don't have the init scripts though? Does anyone even use unicorn without them? (We of course have them).

**Comment by rylwin** [comment]
@DavidAllison Yes. This gem installs the init script with `cap unicorn:setup`. capistrano-unicorn manages unicorn via the shell, but it seems cleaner to install an init script and then use that to control your unicorns. 

The init script seems to be standard enough that it should just be provided by the gem. No reason to have to roll your own (or copy paste) every time you deploy a new project. I don't know why you wouldn't use an init script---that just seems dangerous (unless you're using some other process management daemon).

**Comment by sfsekaran** [comment]
This sounds really nice to me, except for what you said at the very end. What if someone uses God or Monit? I wonder if this would be better in a separate install task. Maybe `cap unicorn:install:unix_init`?

**Comment by rylwin** [comment]
@sfsekaran No reason why multiple process mgmt daemons couldn't be supported--great point.

But how about when you call, for example, `cap unicorn:restart` if the gem knew which tool you are using to manage daemons? So maybe instead of `cap unicorn:install:unix_init` you could: 
- `set :unicorn_management_daemon` to `:init`, `:god`, etc and 
- `cap unicorn:*` would fetch the variable and issue the correct command.

With this technique you could also support not using any process mgmt daemon and just manage unicorn directly like capistrano-unicorn currently does. (And maybe this would be the default)

@sosedoff Do you have any interest in bringing in support for init, god, monit, etc into this gem? I'd be happy to make a pull request for init support.

**Comment by sosedoff** [comment]
@rylwin i have a mixed feelings about this. 

having support to maintain process health is good, but on the other hand it brings too much of functionality into this particular library.

**Comment by sfsekaran** [comment]
Yeah, I'm beginning to feel the same. Maybe keeping it in a separate but compatible gem would be the best option right now. 
—
Sathya Sekaran

**Comment by rylwin** [comment]
I would think the gem would only have to support each process manager in a minimal way:
- Allow users to provide the init/god/monit file 
- Know where to place the file on the app server
- Know what command to run on the server for stop/start/restart

All the work for maintaining process health is left to init/god/monit. This gem wouldn't have to worry about those details.

But if the consensus is that this is too much for this gem, that's fine. I'm only using init, so I'll continue maintaining the init based unicorn capistrano gem over at ValencePM/capistrano-unicorn-init.
