### ISSUE TITLE
mixed env of passenger servers and unicorn server fails to run `unicorn:reload' is only run for servers matching {:roles=>:unicorn, :except=>{:no_release=>true}}, but no servers matched 

### ISSUE THREAD

**Issue by innovia** [sosedoff/capistrano-unicorn#57]
how can I reload in a multistage ?

can it have  :on_no_matching_servers => :continue so that it skips trying to reload when no servers with unicorn role found?

**Comment by innovia** [comment]
never mind solved it!

**Comment by innovia** [comment]
tasks.keys.each do |multistage|
  tasks[multistage].namespace.namespaces[:unicorn].tasks[:reload].options[:roles] = :unicorn
  tasks[multistage].namespace.namespaces[:unicorn].tasks[:reload].options[:on_no_matching_servers] = :continue
end

**Comment by sfsekaran** [comment]
Interesting solution. Either this or you could create your own custom unicorn tasks using the underlying `capistrano_unicorn` API, which can be given different unicorn options per stage, say. Thanks for providing feedback!
